# Generated by Django 4.0.3 on 2022-06-30 08:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import shopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_category_alter_product_section_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='DEFAULT VALUE', max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='get_file_path')),
                ('small_description', models.TextField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0-default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default, 1=Trending')),
                ('tag', models.CharField(max_length=150)),
                ('cart', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=48, verbose_name='fa fa-star')),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=150)),
                ('meta_description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='product_section',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rating',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 30, 8, 48, 23, 202287, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default='DEFAULT VALUE', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(default='DEFAULT VALUE', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(default='DEFAULT VALUE', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='DEFAULT VALUE', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0-default, 1=Hidden'),
        ),
        migrations.AddField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default, 1=Trending'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopping.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.category'),
        ),
    ]
